#!/usr/bin/bash

# TODO:
# - check return code of qdbus ( is clementine running? )

# MAGIC!
# sample output of qdbus when track is
# playing:
# [Argument: (iiii) 0, 0, 0, 0]
# paused:
# [Argument: (iiii) 1, 0, 0, 0]
# stopped:
# [Argument: (iiii) 2, 0, 0, 0]

status=$(qdbus --literal org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetStatus 2>/dev/null | awk '{ gsub(",","",$3); print $3}')
[ -z "$status" ] && exit 15

qdbus org.mpris.clementine /Player org.freedesktop.MediaPlayer.GetMetadata | awk -v status="$status" '
BEGIN {
    if ( status == 1 ) printf "[PAUSED] "
    else if ( status == 2 ) { print "[STOPPED]"; exit 2 }
    else if ( status != 0 ) exit 14     # we should never reach this
}

/artist: / {
    gsub("artist: ","")
    printf $0
    printf " - "
}
/title: / {
    gsub("title: ","")
    printf $0
    printf "\n"
}
'
