#!/usr/bin/env bash

shopt -s nullglob globstar

#typeit=0
#if [[ $1 == "--type" ]]; then
#	typeit=1
#	shift
#fi

prefix="${HOME}"/.local/share/tmenu
template_files=( ${prefix}/**/* )
template_files=( "${template_files[@]#"$prefix"/}" )
template_files=( "${template_files[@]%.txt}" )

template=$(printf '%s\n' "${template_files[@]}" | dmenu "$@")

[[ -n $template ]] || exit

xclip -selection clipboard "${prefix}/${template}.txt"

#if [[ ! $typeit -eq 0 ]]; then
#    xdotool - <<<"type -- $(cat ${prefix}/${template}.txt)"
#fi
exit 0
