#!/bin/bash

dotdir="$HOME/dotfiles"

for i in "$@"; do
    dotfile="$(realpath "$i")"
    [ -x "$dotfile" ] || notexecutable="-m644"
    install -D $notexecutable "$i" "$dotdir/${dotfile/$HOME}"
done
